name: Daily Slack Summary

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch: {}  

concurrency:
  group: daily-slack-summary
  cancel-in-progress: true

jobs:
  run-summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run daily summary
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          CLAUDE_API_KEY:  ${{ secrets.CLAUDE_API_KEY }}
        run: python slack_summary.py
